### ISSUE TITLE
可以让英文单词不出现在第一个候选吗？

### ISSUE THREAD

**Issue by tachikomachann** [mutoe/rime#7]
比如每次我想打“或者”*(hove)，第一个候选词永远是“hove”，但是或者才是我的常用词。还有打“不能”(bung)也是这问题。有办法调整这个顺序么，让英文不要出现在第一个词。 
![image](https://user-images.githubusercontent.com/51024737/157159419-8acf4823-0873-4ed5-9686-3f0fcbc736ba.png) 
![image](https://user-images.githubusercontent.com/51024737/157159444-83408361-47d9-49f4-86d9-475f2a8cf344.png)

**Comment by BreathBlush** [comment]
正好碰到了和你一样的问题，经查找资料，已解决。
用编辑器打开double_pinyin_plus.schema.yaml文件，加入这一行就可以了。
![image](https://user-images.githubusercontent.com/10967857/160263647-f5fe4bd9-9f60-4ee3-97cc-81ae9e0db8a4.png)

**Comment by tachikomachann** [comment]
> 正好碰到了和你一样的问题，经查找资料，已解决。 用编辑器打开double_pinyin_plus.schema.yaml文件，加入这一行就可以了。 ![image](https://user-images.githubusercontent.com/10967857/160263647-f5fe4bd9-9f60-4ee3-97cc-81ae9e0db8a4.png)

太感谢了，已解决。😊
